# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('color', models.CharField(max_length=7)),
                ('exif_make', models.CharField(max_length=30)),
                ('exif_model', models.CharField(max_length=30)),
                ('exif_exposure', models.CharField(max_length=30)),
                ('exif_aparture', models.CharField(max_length=30)),
                ('exif_focul', models.CharField(max_length=30)),
                ('exif_iso', models.CharField(max_length=30)),
                ('location_name', models.CharField(max_length=30)),
                ('location_lat', models.CharField(max_length=30)),
                ('location_long', models.CharField(max_length=30)),
                ('url_raw', models.URLField()),
                ('url_full', models.URLField()),
                ('url_regular', models.URLField()),
                ('url_download', models.URLField()),
                ('url_share', models.URLField()),
                ('user_display_name', models.CharField(max_length=50)),
                ('user_profile_pic', models.URLField()),
            ],
        ),
    ]
