# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsplash', '0002_auto_20170121_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_category',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
