# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsplash', '0005_auto_20170121_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='color',
            field=models.CharField(default='#ECFFC4', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exif_aparture',
            field=models.CharField(default='null', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exif_exposure',
            field=models.CharField(default='null', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exif_focul',
            field=models.CharField(default='null', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exif_iso',
            field=models.CharField(default='null', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exif_make',
            field=models.CharField(default='null', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exif_model',
            field=models.CharField(default='null', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location_lat',
            field=models.FloatField(default='-1', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location_long',
            field=models.FloatField(default='-1', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location_name',
            field=models.CharField(default='null', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_category',
            field=models.CharField(default='null', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user_profile_pic',
            field=models.URLField(default='null', null=True),
        ),
    ]
