# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsplash', '0006_auto_20170121_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='exif_make',
            field=models.CharField(default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location_name',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user_display_name',
            field=models.CharField(max_length=100),
        ),
    ]
