# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsplash', '0008_auto_20170124_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url_custom',
            field=models.URLField(default='none'),
        ),
        migrations.AddField(
            model_name='photo',
            name='url_small',
            field=models.URLField(default='none'),
        ),
        migrations.AddField(
            model_name='photo',
            name='url_thumb',
            field=models.URLField(default='none'),
        ),
    ]
