# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsplash', '0011_auto_20170225_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='exif_aparture',
            field=models.CharField(blank=True, default='none', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exif_exposure',
            field=models.CharField(blank=True, default='none', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exif_focul',
            field=models.CharField(blank=True, default='none', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exif_iso',
            field=models.CharField(blank=True, default='none', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exif_model',
            field=models.CharField(blank=True, default='none', max_length=30, null=True),
        ),
    ]
