# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsplash', '0013_auto_20170225_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_height', models.CharField(max_length=100)),
                ('device_width', models.CharField(max_length=100)),
            ],
        ),
    ]
