# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('unsplash', '0015_devicedata_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
