# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unsplash', '0016_auto_20170301_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedata',
            name='unique_id',
        ),
    ]
