# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsplash', '0020_auto_20170305_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedlist',
            name='curated_is_curated',
            field=models.BooleanField(default=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='curatedlist',
            name='curated_is_featured',
            field=models.BooleanField(default=False, max_length=30),
        ),
    ]
