# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unsplash', '0021_auto_20170305_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='curated_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unsplash.CuratedList'),
        ),
    ]
