# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsplash', '0023_auto_20170305_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionlist',
            name='curated_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
