# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-04 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unsplash', '0024_auto_20170305_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='curated_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='unsplash.CollectionList'),
            preserve_default=False,
        ),
    ]
